server:
  port: 6666
  servlet:
    context-path: /gamedatapicker
  ssl:
    key-store: /root/.acme.sh/cntytw.com_ecc/cntytw.com.keystore
    keyStoreType: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}

spring:
  application:
    name: GameDataPicker
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/game-data-picker?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: ${KEYSTORE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 4
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 6
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  #sql:
  #  init:
  #    schema-locations:
  #      - "classpath:dbinit/schema.sql"
  #    data-locations:
  #      - "classpath:dbinit/data.sql"

logging:
  level:
    com.cntytw: debug
    com.cntytw.datapicker.dologalaxy.mapper: trace
    com.baomidou.mybatisplus: trace
    org.springframework.jdbc: trace

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cntytw.datapicker.dologalaxy.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      #db-type: mysql
    #刷新mapper 调试神器
    #refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
